spring.application.name=TechCup
spring.profiles.active=prod

server.port=${PORT:80}

spring.datasource.url=jdbc:postgresql://techcup-postgres.postgres.database.azure.com:5432/techcupdb?sslmode=require
spring.datasource.username=techcup@techcup-postgres
spring.datasource.password=Hola12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.user.name=techcup
spring.security.user.password=techcup2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.file.name=logs/tech-cup-LXJJE.log
