spring.application.name=TechCup
spring.profiles.active=prod


# Puerto para Azure App Service
server.port=${SERVER_PORT:${PORT:8080}}

# Configuración PostgreSQL Azure
spring.datasource.url=jdbc:postgresql://techcup-postgres-nuevo.postgres.database.azure.com:5432/DBtechcup?sslmode=require

# 
spring.datasource.username=LXJJE@techcup-postgres-nuevo
spring.datasource.password=Hola12345

spring.datasource.driver-class-name=org.postgresql.Driver

# Usuario de seguridad Spring
spring.security.user.name=techcup
spring.security.user.password=techcup2026

# Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logs
logging.file.name=tech-cup-LXJJE.log
