spring.application.name=TechCup
spring.profiles.active=prod

spring.datasource.url=jdbc:postgresql://localhost:5432/TechCup_lab8db
spring.datasource.username=LXJJE
spring.datasource.password=0LXJJE0
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.file.name=logs/tech-cup-LXJJE.log
